# Generated by Django 5.2.17 on 2026-08-20 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hours', models.PositiveIntegerField(default=0)),
                ('rate', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('rejection_reason', models.TextField(blank=True, default=None, null=True)),
                ('approved_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approvedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_submissions', to=settings.AUTH_USER_MODEL)),
                ('assignId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.assignedtask')),
            ],
        ),
        migrations.CreateModel(
            name='TimesheetStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timesheet_status', models.CharField(choices=[('Requested', 'Requested'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Requested', max_length=50, null=True)),
                ('weeknumber', models.IntegerField(db_index=True, default=None, null=True)),
                ('submission_status', models.BooleanField(default=False)),
                ('action_status', models.BooleanField(default=False)),
                ('weekyear', models.IntegerField(default=None, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('unlock_reason', models.CharField(default=None, max_length=1000, null=True)),
                ('unlock_status', models.CharField(choices=[('Requested', 'Requested'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Requested', max_length=10, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('comments', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheet_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_permissions': (),
                'indexes': [models.Index(fields=['uid', 'weeknumber'], name='api_timeshe_uid_id_6c057d_idx')],
            },
        ),
    ]
