# Generated by Django 5.2.17 on 2026-08-31 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheetstatus',
            name='timesheet_status',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Submitted', 'Submitted'), ('Unlocked', 'Unlocked'), ('Unlock Rejected', 'Unlock Rejected')], default='Requested', max_length=50, null=True),
        ),
    ]
