# Generated by Django 4.2.16 on 2026-08-06 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(db_index=True, max_length=255)),
                ('task_name', models.CharField(db_index=True, max_length=255)),
                ('start_date', models.DateField(blank=True, db_index=True, null=True)),
                ('end_date', models.DateField(blank=True, db_index=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('quotation', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('system_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('customer_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('customer_code', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('quoted_date', models.DateField(blank=True, db_index=True, null=True)),
                ('milestone', models.IntegerField(blank=True, db_index=True, null=True)),
                ('milestone_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('assign_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('assign_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date'],
                'indexes': [models.Index(fields=['assign_to', 'project'], name='api_taskass_assign__20b254_idx'), models.Index(fields=['customer_code', 'quoted_date'], name='api_taskass_custome_c4d707_idx'), models.Index(fields=['assign_by'], name='api_taskass_assign__f25d86_idx'), models.Index(fields=['start_date', 'end_date'], name='api_taskass_start_d_f9c101_idx')],
            },
        ),
    ]
