# Generated by Django 4.2.16 on 2026-08-06 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_taskassignment'),
    ]

    operations = [
        # Rename the existing TaskAssignment model to AssignedTask to keep the
        # existing table and avoid SQLite remake-table issues.
        migrations.RenameModel(
            old_name='TaskAssignment',
            new_name='AssignedTask',
        ),
        # Rename the old `project` CharField to `project_name` so we can add
        # a new integer `project` field alongside it.
        migrations.RenameField(
            model_name='assignedtask',
            old_name='project',
            new_name='project_name',
        ),
        # Add new integer `project` and `task` fields required by the new model
        migrations.AddField(
            model_name='assignedtask',
            name='project',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='assignedtask',
            name='task',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        # Create the Submission model
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hours', models.PositiveIntegerField(default=0)),
                ('rate', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('rejection_reason', models.TextField(blank=True, default=None, null=True)),
                ('approved_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approvedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_submissions', to=settings.AUTH_USER_MODEL)),
                ('assignId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.assignedtask')),
            ],
        ),
        # Add indexes on the renamed/modified AssignedTask model
        migrations.AddIndex(
            model_name='assignedtask',
            index=models.Index(fields=['assign_to', 'project'], name='api_assigne_assign__f8e993_idx'),
        ),
        migrations.AddIndex(
            model_name='assignedtask',
            index=models.Index(fields=['customer_code', 'quoted_date'], name='api_assigne_custome_77cbb3_idx'),
        ),
        migrations.AddIndex(
            model_name='assignedtask',
            index=models.Index(fields=['assign_by'], name='api_assigne_assign__315ab9_idx'),
        ),
        migrations.AddIndex(
            model_name='assignedtask',
            index=models.Index(fields=['start_date', 'end_date'], name='api_assigne_start_d_a68c03_idx'),
        ),
    ]
