# Generated by Django 5.2.17 on 2026-08-27 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_timesheetstatus_timesheet_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheetstatus',
            name='unlock_status',
        ),
    ]
