# Generated by Django 5.2.17 on 2026-09-01 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_convert_submission_hours_to_seconds'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timesheetstatus',
            options={},
        ),
    ]
