# Generated by Django 4.2.16 on 2026-08-06 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_assignedtask_submission_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeSheetEntry',
        ),
        migrations.RemoveIndex(
            model_name='assignedtask',
            name='api_taskass_assign__20b254_idx',
        ),
        migrations.RemoveIndex(
            model_name='assignedtask',
            name='api_taskass_custome_c4d707_idx',
        ),
        migrations.RemoveIndex(
            model_name='assignedtask',
            name='api_taskass_assign__f25d86_idx',
        ),
        migrations.RemoveIndex(
            model_name='assignedtask',
            name='api_taskass_start_d_f9c101_idx',
        ),
    ]
