# Generated by Django 4.2.16 on 2026-08-06 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_delete_timesheetentry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimesheetStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timesheet_status', models.CharField(choices=[('Requested', 'Requested'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Requested', max_length=50, null=True)),
                ('weeknumber', models.IntegerField(db_index=True, default=None, null=True)),
                ('submission_status', models.BooleanField(default=False)),
                ('action_status', models.BooleanField(default=False)),
                ('weekyear', models.IntegerField(default=None, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('unlock_reason', models.CharField(default=None, max_length=1000, null=True)),
                ('unlock_status', models.CharField(choices=[('Requested', 'Requested'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Requested', max_length=10, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('comments', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheet_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_permissions': (),
                'indexes': [models.Index(fields=['uid', 'weeknumber'], name='api_timeshe_uid_id_6c057d_idx')],
            },
        ),
    ]
