# Generated by Django 4.2.16 on 2026-08-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_task_milestone'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='assignedtask',
            name='api_assigne_assign__f8e993_idx',
        ),
        migrations.RemoveIndex(
            model_name='assignedtask',
            name='api_assigne_custome_77cbb3_idx',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='code',
            new_name='customer_code',
        ),
        migrations.RemoveField(
            model_name='assignedtask',
            name='customer_code',
        ),
        migrations.RemoveField(
            model_name='assignedtask',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='assignedtask',
            name='milestone',
        ),
        migrations.RemoveField(
            model_name='assignedtask',
            name='milestone_name',
        ),
        migrations.RemoveField(
            model_name='assignedtask',
            name='project',
        ),
        migrations.RemoveField(
            model_name='assignedtask',
            name='project_name',
        ),
        migrations.RemoveField(
            model_name='assignedtask',
            name='quotation',
        ),
        migrations.RemoveField(
            model_name='assignedtask',
            name='quoted_date',
        ),
        migrations.RemoveField(
            model_name='assignedtask',
            name='system_name',
        ),
        migrations.RemoveField(
            model_name='assignedtask',
            name='task',
        ),
        migrations.RemoveField(
            model_name='assignedtask',
            name='task_name',
        ),
        migrations.RemoveField(
            model_name='milestone',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='milestone',
            name='external_id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.RemoveField(
            model_name='task',
            name='external_id',
        ),
        migrations.AddField(
            model_name='project',
            name='customer_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='quotation',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='quoted_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='system_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='assignedtask',
            index=models.Index(fields=['assign_to', 'project_obj'], name='api_assigne_assign__79bf64_idx'),
        ),
    ]
