# Generated by Django 4.2.16 on 2026-08-06 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_assignedtask_api_assigne_assign__f8e993_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedtask',
            name='milestone_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to='api.milestone'),
        ),
        migrations.AlterField(
            model_name='assignedtask',
            name='project_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to='api.project'),
        ),
        migrations.AlterField(
            model_name='assignedtask',
            name='task_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to='api.task'),
        ),
        migrations.AlterField(
            model_name='project',
            name='customer_code',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='quotation',
            field=models.CharField(blank=True, db_index=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='api.milestone'),
        ),
    ]
