# Generated by Django 4.2.16 on 2026-08-06 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_role_users_userprofile_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('department', 'Department'), ('team', 'Team')], default='department', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('name', 'type')},
            },
        ),
        migrations.CreateModel(
            name='UserDepartmentTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('department_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_mappings', to='users.departmentteam')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_mappings', to='users.userprofile')),
            ],
            options={
                'unique_together': {('profile', 'department_team')},
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='department_teams',
            field=models.ManyToManyField(blank=True, related_name='profiles', through='users.UserDepartmentTeam', to='users.departmentteam'),
        ),
    ]
