# Generated by Django 4.2.16 on 2026-08-06 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_departmentteam_userdepartmentteam_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DepartmentTeam',
            new_name='Department',
        ),
        migrations.RenameField(
            model_name='userdepartmentteam',
            old_name='department_team',
            new_name='department',
        ),
        migrations.AlterUniqueTogether(
            name='userdepartmentteam',
            unique_together={('profile', 'department')},
        ),
    ]
