# Generated by Django 4.2.16 on 2026-08-06 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_userdepartmentteam_userdepartment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='department_teams',
            new_name='department',
        ),
    ]
