# Generated by Django 5.2.17 on 2026-08-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phases',
            options={'verbose_name': 'Phase', 'verbose_name_plural': 'Phases'},
        ),
        migrations.AlterField(
            model_name='phases',
            name='cost_category',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='phases',
            constraint=models.UniqueConstraint(fields=('phase', 'cost_category'), name='unique_phase_cost_category'),
        ),
    ]
