# Generated by Django 4.2.16 on 2026-08-10 03:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Self_Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=30, unique=True)),
                ('task', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=2000)),
                ('est_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('target_date', models.DateField(default=django.utils.timezone.now)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('current_status', models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('accepted', 'Accepted'), ('on hold', 'On Hold'), ('in progress', 'In Progress'), ('feedback provided', 'Feedback Provided'), ('completed', 'Completed'), ('closed', 'Closed'), ('rejected', 'Rejected'), ('recall requested', 'Recall Requested'), ('recall successful', 'Recall Successful'), ('modified', 'Modified'), ('not-satisfied', 'Not-Satisfied'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(default='open', max_length=10)),
                ('ticket_number', models.CharField(blank=True, max_length=30, null=True)),
                ('reminder_interval', models.IntegerField(default=1)),
                ('comments', models.CharField(default=None, max_length=500)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_self_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('view_self_tickets', 'Handle Self Ticket'), ('view_managementoverview', 'Handle Management Overview'), ('view_report', 'Handle Ticket Report')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=30, unique=True)),
                ('task', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=2000)),
                ('est_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('target_date', models.DateField(default=django.utils.timezone.now)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('current_status', models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('accepted', 'Accepted'), ('on hold', 'On Hold'), ('in progress', 'In Progress'), ('feedback provided', 'Feedback Provided'), ('completed', 'Completed'), ('closed', 'Closed'), ('rejected', 'Rejected'), ('recall requested', 'Recall Requested'), ('recall successful', 'Recall Successful'), ('modified', 'Modified'), ('not-satisfied', 'Not-Satisfied'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('rating', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_ticket', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tickets', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='auth.group')),
            ],
            options={
                'permissions': [('view_ticket', 'Handle View Ticket'), ('add_ticket', 'Handle Create Ticket')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Ticket_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('accepted', 'Accepted'), ('on hold', 'On Hold'), ('in progress', 'In Progress'), ('feedback provided', 'Feedback Provided'), ('completed', 'Completed'), ('closed', 'Closed'), ('rejected', 'Rejected'), ('recall requested', 'Recall Requested'), ('recall successful', 'Recall Successful'), ('modified', 'Modified'), ('not-satisfied', 'Not-Satisfied'), ('cancelled', 'Cancelled')], max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_assignments', to=settings.AUTH_USER_MODEL)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs_changed', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='tickets.ticket')),
            ],
            options={
                'ordering': ['-created_at'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Ticket_File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='%d-%m-%Y')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='tickets.ticket')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Self_Ticket_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_self_log', to=settings.AUTH_USER_MODEL)),
                ('self_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selfLogs', to='tickets.self_ticket')),
            ],
            options={
                'ordering': ['-created_at'],
                'default_permissions': (),
            },
        ),
    ]
