# Generated by Django 5.2.17 on 2026-09-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_internal',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
