# Generated by Django 4.2.16 on 2026-08-10 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='self_ticket',
            name='comments',
        ),
    ]
