# Generated by Django 5.2.17 on 2026-09-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_is_internal_alter_self_ticket_task_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='self_ticket',
            name='task',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='task',
            field=models.CharField(max_length=100),
        ),
    ]
