# Generated by Codex on 2026-09-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_self_ticket_task_alter_ticket_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='self_ticket',
            name='alarm',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
