# Generated by Django 4.2.16 on 2026-09-02 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_update_ticket_rbac_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_external',
            field=models.BooleanField(default=False),
        ),
    ]
