# Generated by Django 4.2.16 on 2026-08-06 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_departmentteam_department_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserDepartmentTeam',
            new_name='UserDepartment',
        ),
    ]
