# Generated by Django 4.2.16 on 2026-08-06 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0007_rename_department_teams_userprofile_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='type',
            field=models.CharField(choices=[('department', 'Software'), ('team', 'Software')], default='department', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='reporting_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to=settings.AUTH_USER_MODEL),
        ),
    ]
