# Generated by Django 4.2.16 on 2026-08-14 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_role_permissions'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userdepartment',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userdepartment',
            name='department',
        ),
        migrations.RemoveField(
            model_name='userdepartment',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='department',
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='UserDepartment',
        ),
    ]
