# Generated by Django 4.2.16 on 2026-08-14 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0010_alter_userdepartment_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='auth.group'),
        ),
    ]
