# Generated by Django 5.2.17 on 2026-08-18 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_departmentmanager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='department',
        ),
    ]
