# Generated by Codex on 2026-08-31

from django.db import migrations


PAGE_PERMISSIONS = [
    ('access_home', 'Can access Home page'),
    ('access_self_tickets', 'Can access Do List page'),
    ('access_tickets', 'Can access Tickets page'),
    ('access_timesheet', 'Can access Timesheet page'),
    ('access_executive_overview', 'Can access Executive Overview page'),
    ('access_team_analysis', 'Can access Team Analysis page'),
    ('access_user_management', 'Can access User Management page'),
    ('access_role_management', 'Can access Role Management page'),
    ('access_project_configuration', 'Can access Project Configuration page'),
    ('access_phase_configuration', 'Can access Phase Configuration page'),
]


def create_and_assign_page_permissions(apps, schema_editor):
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Permission = apps.get_model('auth', 'Permission')
    Role = apps.get_model('users', 'Role')

    role_content_type = ContentType.objects.get(app_label='users', model='role')
    page_permissions = {}

    for codename, name in PAGE_PERMISSIONS:
        permission, _ = Permission.objects.get_or_create(
            content_type=role_content_type,
            codename=codename,
            defaults={'name': name},
        )
        page_permissions[codename] = permission

    permission_map = {
        'access_self_tickets': {'view_self_tickets', 'view_self_ticket'},
        'access_tickets': {'view_ticket'},
        'access_timesheet': {'view_submission'},
        'access_executive_overview': {'view_managementoverview', 'view_report'},
        'access_team_analysis': {'view_managementoverview'},
        'access_user_management': {'view_user'},
        'access_role_management': {'view_role'},
        'access_project_configuration': {'view_project'},
        'access_phase_configuration': {'view_project'},
    }

    for role in Role.objects.prefetch_related('permissions').all():
        current_codenames = set(role.permissions.values_list('codename', flat=True))
        permissions_to_add = [page_permissions['access_home']]

        for access_codename, source_codenames in permission_map.items():
            if current_codenames.intersection(source_codenames):
                permissions_to_add.append(page_permissions[access_codename])

        role.permissions.add(*permissions_to_add)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_userprofile_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={
                'permissions': [
                    ('access_home', 'Can access Home page'),
                    ('access_self_tickets', 'Can access Do List page'),
                    ('access_tickets', 'Can access Tickets page'),
                    ('access_timesheet', 'Can access Timesheet page'),
                    ('access_executive_overview', 'Can access Executive Overview page'),
                    ('access_team_analysis', 'Can access Team Analysis page'),
                    ('access_user_management', 'Can access User Management page'),
                    ('access_role_management', 'Can access Role Management page'),
                    ('access_project_configuration', 'Can access Project Configuration page'),
                    ('access_phase_configuration', 'Can access Phase Configuration page'),
                ],
            },
        ),
        migrations.RunPython(create_and_assign_page_permissions, migrations.RunPython.noop),
    ]
