# Generated by Django 5.2.17 on 2026-09-03 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_role_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'permissions': [('access_self_tickets', 'Can access Do List page'), ('access_tickets', 'Can access Tickets page'), ('access_timesheet', 'Can access Timesheet page'), ('access_document_template', 'Can access Document Template page'), ('access_lesson_learnt', 'Can access Lesson Learnt page'), ('access_system_suggetions', 'Can access System Suggetions page'), ('access_timesheet_log', 'Can access Timesheet Log page'), ('access_executive_overview', 'Can access Executive Overview page'), ('access_team_analysis', 'Can access Team Analysis page'), ('access_user_management', 'Can access User Management page'), ('access_role_management', 'Can access Role Management page'), ('access_project_configuration', 'Can access Project Configuration page'), ('access_phase_configuration', 'Can access Phase Configuration page')]},
        ),
    ]
